name: flutter_xkom
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  slide_countdown_clock: ^1.0.3
  url_launcher: ^5.4.11
  flutter_boxicons: ^1.1.1
  percent_indicator: ^2.1.3
  clean_swiper: ^0.0.5
  font_awesome_flutter: ^8.8.1
  characters: ^1.0.0
  sailor: ^0.7.1
  carousel_slider: ^2.2.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/banners/
    - assets/images/icons/
    - assets/images/products/
    - assets/images/graphics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Calibri
      fonts:
       - asset: assets/fonts/Calibri-Regular.ttf
       - asset: assets/fonts/Calibri-Italic.ttf
         style: italic
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
